import anthropic
import os
from datetime import datetime

timestamp=datetime.now().strftime("%Y-%m-%d-%H-%M") 

#calling the anthropic api key
try:
	client=anthropic.Anthropic(api_key=os.environ.get("ANTHROPIC_API_KEY"))
except Exception as e:
	print("API KEY Not found/failed/wrong due to connectivity issues")
	print(f"Error details: {e}")
	exit()

def threat_mapping(threat):
	""" 
	Calls Claude API to generate the MITRE ATT&CK mapping to the given threat.
	Returns the result as string, or NONE if API Call fails
	"""
	try:	
		prompt="You are an expert Threat Hunter who is a MITRE expert and whose job is to analyse the given threat for its suspicious behaviour and map that threat to MITRE tactic and its respective technique ID. Make sure you give the output in the following format- Tactic: <tactic name>\n Technique ID: <T####.###>\n Technique Name: <name>.Also remember that multiple MITRE techniques are allowed and each and every such tactic and technique should be displayed in the exact format as mentioned.\n\n" + threat 
		message=client.messages.create(
			model="claude-sonnet-4-20250514",
			max_tokens=8192,
			messages=[
				{"role":"user", "content":prompt}
		])
		return message.content[0].text
	except Exception as e:
		print(f"Error Details: {e}")
		print("This threat failed to be analysed, moving onto next. Check Manually")		
		return None


	
def generate_query(threat, siem):
	"""
  	 Calls Claude API to generate SIEM queries based on threat description.
   	 Returns query as string, or None if API call fails.
    	"""
	try:	
		prompt="You are an expert Threat Hunter whose job is to analyse suspicious behavior. This is a suspicious behaviour, analyse it and generate a necessary " + siem + "Query for this. \n\n" + threat
		message=client.messages.create(
			model="claude-sonnet-4-20250514",
			max_tokens=8192,
			messages=[
				{"role":"user", "content":prompt}
		])
		return message.content[0].text
	except Exception as e:
		print(f"Error Details: {e}")
		print("This threat failed to analysed, moving onto next. Check Manually")

		return None

print("Threat Hunt Query Generator")


#asking for user inputs of threat and the siem they want to use

threat = input("Describe the suspicious behaviour: ")

while True:

	siem=input("What SIEM tool do you want to use: Splunk, MS Sentinel, Elastic?").lower()
	if siem == "splunk":
		siem="Splunk"
		break
	elif siem in [ "ms sentinel","sentinel"]:
		siem = "MS Sentinel"
		break
	elif siem in ["elastic" , "elk"]:
		siem = "Elastic"
		break
	else:
		print('Please type in correct spelling: "Splunk", "MS Sentinel" or "Elastic" ?')
		continue


retry=0  #counter variable to track the number of attempts or retries made in case any error occurs


while True:
		
	#calling the generate_query function

	result=generate_query(threat, siem)

	if result is None:
		print("API Call failed! Try again... ")	
		retry+=1
		if retry==3:
			print("Unable to call API, check the file or key manually")
			break
		continue

	#making sure that the output that is being generated by the Claude API is complete in its entirety

	if result.count("```")%2==0:	
		mitre_mapping=threat_mapping(threat)
		
		if mitre_mapping is None:
			print("API Call failed! Try again... ")	
			retry+=1
			if retry==3:
				print("Unable to call API, check the file or key manually")
				break
			continue
		print(result+"=="*50+"\nMITRE ATT&CK MAPPING\n"+mitre_mapping)

		threat_report=f"query_history.txt"
		with open (threat_report, "a", encoding="utf-8") as f:
			f.write(f"Threat: {threat}\n")
			f.write(f"SIEM: {siem}\n")
			f.write(f"MITRE MAPPING: {mitre_mapping}\n") 
			f.write(f"Generated Query: {result}\n")
			f.write(f"Timestamp: {timestamp}\n") #saving the report with proper timestamp
			f.write("\n" + "="*200 + "\n")
			print(f"Done! Report saved to {threat_report}") 
			break
	else:
		retry+=1
		print(f"Attempt {retry}: Incomplete Query generated!Running again.....")

		if retry==3:
			print("Unable to generate the full query for the provided threat. Do it manually.")
			break
		
	
